title: Dulces Tradicionales Mexicanos
description: Blog para la clase de Introducción al Desarrollo de Aplicaciones de Red
theme: cayman
baseurl: "/stephancandles.github.io"  # Importante para project pages
url: "https://stormor01.github.io"
